### ISSUE TITLE
Build with Fuseki snapshots doesn't work under Travis CI

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1121]
The upcoming Fuseki version 4.0.0-SNAPSHOT is a major upgrade and seems to need a more recent Java version than 3.*. As a consequence of this, Travis CI jobs that use the Fuseki snapshot started getting stuck and they only get killed after 2 hours, massively slowing down builds.

I created PR #1120 to disable the fuseki snapshot build jobs for now, but I think we want to get them back running again. This needs investigation, probably we just need to ensure that a more recent Java version is available in the Travis CI environment.

Here is the Java error/traceback:

```
Error: A JNI error has occurred, please check your installation and try again

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/jena/fuseki/cmd/FusekiCmd has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by kinow** [comment]
Maybe now this is fixed in GH Actions?

**Comment by osma** [comment]
Not relevant anymore, so closing. We are not using Fuseki snapshots in CI.
