### ISSUE TITLE
Invalid dates break concept page

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#253]
## At which URL did you encounter the problem?
http://dev.finto.fi/ysa/fi/page/Y97438

## What steps will reproduce the problem?
1. Go to "metsävauriot" in YSA

## What is the expected output? What do you see instead?

Expected to get concept page, but getting blank page. Error log:

[Thu May 07 16:29:20 2015] [error] [client 128.214.71.212] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (1986-21-00) at position 6 (1): Unexpected character' in /var/www/dev.finto.fi/vendor/easyrdf/easyrdf/lib/EasyRdf/Literal/Date.php:97\nStack trace:\n#0 /var/www/dev.finto.fi/vendor/easyrdf/easyrdf/lib/EasyRdf/Literal/Date.php(97): DateTime->__construct('1986-21-00')\n#1 /var/www/dev.finto.fi/model/ConceptPropertyValueLiteral.php(45): EasyRdf_Literal_Date->getValue()\n#2 /var/www/dev.finto.fi/model/ConceptProperty.php(67): ConceptPropertyValueLiteral->getLabel('fi')\n#3 /var/www/dev.finto.fi/model/Concept.php(303): ConceptProperty->addValue(Object(ConceptPropertyValueLiteral))\n#4 [internal function]: Concept->getProperties()\n#5 /var/www/dev.finto.fi/vendor/twig/twig/lib/Twig/Template.php(437): call_user_func_array(Array, Array)\n#6 /tmp/onki-light-template-cache/84/84/20176dff2d539bfe46efe0ae2ca3.php(364): Twig_Template->getAttribute(Object(Concept), 'properties')\n#7 /var/www/dev.finto.fi/vendor/twig/twig/lib/Twig/Templ in /var/www/dev.finto.fi/vendor/twig/twig/lib/Twig/Template.php on line 279, referer: http://dev.finto.fi/ysa/fi/

The problem is the dct:created value for this concept: "1986-21-00"^^xsd:date

This is obviously not a valid date, but Skosmos should not break completely. I suggest showing the date as it is, in cases like this where it cannot be parsed.

**Comment by osma** [comment]
We need a unit test for this.

**Comment by osma** [comment]
Still need unit test
