### ISSUE TITLE
YSO concept pages broken

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#289]
## At which URL did you encounter the problem?
http://dev.finto.fi/yso/fi/page/p20945

## What steps will reproduce the problem?
1. Open YSO concept page, e.g. above URL

## What is the expected output? What do you see instead?

Getting blank page. Error in log:

[Tue Sep 15 15:45:32 2015] [error] [client 128.214.223.217] PHP Fatal error:  Uncaught exception 'Exception' with message 'Vocabulary id 'Allfo' not found in configuration.' in /var/www/dev.finto.fi/model/Model.php:416\nStack trace:\n#0 /var/www/dev.finto.fi/controller/WebController.php(73): Model->getVocabulary('Allfo')\n#1 [internal function]: {closure}('http://www.yso....', 'Allfo', 'sv', 'page', 'sv')\n#2 /tmp/onki-light-template-cache/84/84/20176dff2d539bfe46efe0ae2ca3.php(898): call_user_func_array(Object(Closure), Array)\n#3 /var/www/dev.finto.fi/vendor/twig/twig/lib/Twig/Template.php(264): __TwigTemplate_848420176dff2d539bfe46efe0ae2ca3->doDisplay(Array, Array)\n#4 /var/www/dev.finto.fi/vendor/twig/twig/lib/Twig/Template.php(238): Twig_Template->displayWithErrorHandling(Array, Array)\n#5 /tmp/onki-light-template-cache/78/be/e3bde6a7268c7c323114145a0c0e.php(59): Twig_Template->display(Array)\n#6 [internal function]: __TwigTemplate_78bee3bde6a7268c7c323114145a0c0e->block_content(Array, Array)\n#7 /var/www/dev.finto.fi/vendor/twig/twig/lib/Twig/Template.php(133): call_user_func(Array, Arra in /var/www/dev.finto.fi/vendor/twig/twig/lib/Twig/Template.php on line 279

**Comment by osma** [comment]
Fixed in 3e3459e125ca7736fbf8e624c97ee9464d21f839
