### ISSUE TITLE
Provide a "GraphDB" dialect for full-text search

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#628]
I like GraphDB. It would be nice if Skosmos can talk to GraphDB using its full-text operators. 
See the documentation at http://graphdb.ontotext.com/documentation/free/lucene-graphdb-connector.html and also https://stackoverflow.com/questions/43517064/how-to-create-a-custom-analyzerfactory-in-graphdb-full-text-search.
I will investigate and provide a patch by looking at what already exists for JenaText.

**Comment by osma** [comment]
Contributions like this are always welcome! But it would be good to be able to have unit tests for this functionality that can run in Travis CI. I wonder if that's possible, given the commercial nature of GraphDB? If downloading and running a GraphDB installation under Travis seems difficult, maybe a stub implementation could be used instead.

**Comment by tfrancart** [comment]
Thanks, I should have seen this. Here is the latest quesry I see in the log file :

```
[2017-10-10 09:58:20] INFO [qid 99385] SPARQL query:
CONSTRUCT {
  <http://data.legilux.public.lu/resource/authority/legal-institution-history> ?property ?value .
} FROM <http://data.legilux.public.lu/resource/authority/legal-institution-history/graph> WHERE {
  <http://data.legilux.public.lu/resource/authority/legal-institution-history> ?property ?value .
  FILTER (?property != skos:hasTopConcept)
}
[2017-10-10 09:58:20] INFO [qid 99385] result: 12 rows returned in 106 ms
```

It seems it is executed correctly. Then the error in the apache log :

```
Tue Oct 10 09:58:20.240189 2017] [:error] [pid 1314] [client 109.74.87.2:37562] PHP Fatal error:  Uncaught Error: Call to undefined method EasyRdf_Sparql_Result::resource() in /var/lib/skosmos/model/Vocabulary.php:144\nStack trace:\n#0 /var/lib/skosmos/vendor/twig/twig/lib/Twig/Template.php(680): Vocabulary->getInfo('fr')\n#1 /tmp/skosmos-template-cache/b4/b438a52156ba66e79e559db8c29b8e52729c0ad9707262a507b62dae7412cf29.php(33): Twig_Template->getAttribute(Object(Vocabulary), 'info', Array, 'method')\n#2 /var/lib/skosmos/vendor/twig/twig/lib/Twig/Template.php(438): __TwigTemplate_582ccf7fc687f49fd0eba2baa31441b1f2ce99184d5fda00ae3ba6d804d3ef3a->doDisplay(Array, Array)\n#3 /var/lib/skosmos/vendor/twig/twig/lib/Twig/Template.php(406): Twig_Template->displayWithErrorHandling(Array, Array)\n#4 /tmp/skosmos-template-cache/9e/9e144ce04ac068de9c5f43446bf36669bd75f2b3d8970b749ed17f27e4e2e40f.php(188): Twig_Template->display(Array)\n#5 /var/lib/skosmos/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_72284e08262d094ed9ca748c5808d2ecb1cd528dd6e930f9045576b893892b0a->block_content(Array, Array)\n#6 /tmp/skosmos-t in /var/lib/skosmos/model/Vocabulary.php on line 144, referer: http://vocabs.sparna.fr/skosmos/fr/
```

**Comment by osma** [comment]
I suspect this is a content negotiation problem between EasyRdf and GraphDB. Is there any chance you could peek at the relevant HTTP headers, especially Accept (request) and Content-Type (response)?

You could do this with ngrep watching for traffic, or using a HTTP proxy with logging, or by editing the EasyRdf code (Client.php IIRC)

You could also write a minimal PHP script that runs the CONSTRUCT query using EasyRdf.

If GraphDB returns something that EasyRdf doesn't recognize as an RDF graph, things go wrong...
