### ISSUE TITLE
Configuration migration script issue

### ISSUE THREAD

**Issue by danmichaelo** [NatLibFi/Skosmos#801]
In my old `config.inc`, I had the default value for `LOG_FILE_NAME`:

```
define ("LOG_FILE_NAME", NULL);
```

This was migrated into

```
skosmos:logFileName ""
```

which caused the following error:

```
Fatal error: Uncaught LogicException: Missing stream url, the stream can not be opened. This may be caused by a premature call to close(). in /var/www/skosmos/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:95 Stack trace: #0 /var/www/skosmos/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array) #1 /var/www/skosmos/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /var/www/skosmos/vendor/monolog/monolog/src/Monolog/Logger.php(546): Monolog\Logger->addRecord(200, '[qid 32579] SPA...', Array) #3 /var/www/skosmos/model/sparql/GenericSparql.php(90): Monolog\Logger->info('[qid 32579] SPA...') #4 /var/www/skosmos/model/sparql/GenericSparql.php(607): GenericSparql->query('CONSTRUCT {\n <...') #5 /var/www/skosmos/model/Vocabulary.php(143): GenericSparql->queryConceptScheme('http://data.ub....') #6 /var/www/skosmos/vendor/twig/twig/lib/Twig/Extension/Core.php(1605): Vocabulary->getInfo('nb in /var/www/skosmos/view/vocab-shared.twig on line 9
```

Fixed easily by commenting out the line:

```
# skosmos:logFileName ""
```

But would be good if the migration script automatically did this.

**Comment by danmichaelo** [comment]
Suggested fix: Change `defined('LOG_FILE_NAME')` to `defined('LOG_FILE_NAME') && ! empty(LOG_FILE_NAME)` on [line 72](https://github.com/NatLibFi/Skosmos/blob/master/migrate-config.php#L72)

**Comment by kinow** [comment]
Sounds like a valid change. I can test it if you would like to submit a pull request. Otherwise I can prepare it and wait for somebody else to test it.

**Comment by osma** [comment]
Thanks for the report and the suggested fix. Sounds good to me. A PR from either of you would be very nice.
